### ISSUE TITLE
Gripper velocity and force can only be configured by editing the URDF 

### ISSUE THREAD

**Issue by pac48** [PickNikRobotics/ros2_robotiq_gripper#43]
The gripper closing speed and closing force should be configurable at runtime.  The robotiq controller does not provide a mechanism to set the speed and force. The problem can be fixed by adding ROS parameters to robotiq controller and slightly modifying the `hardware_interface` to export interfaces to control force and velocity.

**Comment by pac48** [comment]
Blocked by https://github.com/PickNikRobotics/moveit_studio/issues/6256

**Comment by nbbrooks** [comment]
I noticed https://github.com/PickNikRobotics/moveit_studio/issues/6256 is closed (ros2 control maintainers fixed it another way) - does that mean this is unblocked?

**Comment by pac48** [comment]
> I noticed [PickNikRobotics/moveit_studio#6256](https://github.com/PickNikRobotics/moveit_studio/issues/6256) is closed (ros2 control maintainers fixed it another way) - does that mean this is unblocked?

I think it is unblocked now, but still waiting on this PR to go in https://github.com/ros-controls/ros2_controllers/pull/1002

**Comment by nbbrooks** [comment]
It's merged!!!
