### ISSUE TITLE
robotiq_85_2f_gripper appears broken in Gazebo - no mimic_joints

### ISSUE THREAD

**Issue by ProfJust** [PickNikRobotics/ros2_robotiq_gripper#49]
The parallel kinematic with mimic_joints used does not work in ROS2-Humble with Gazebo-Classic. The Gripper is broken.

This the same in this issue https://github.com/ros-industrial/robotiq/issues/150.

![Screenshot from 2024-05-23 11-31-30](https://github.com/PickNikRobotics/ros2_robotiq_gripper/assets/16134593/49c27f4e-9c84-4f7f-be5d-33e0a03151db)

Unfortunately there is no [roboticsgroup_gazebo_plugin] (https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins) available for ROS2.

How can I get this gripper working with ROS2?

**Comment by theanhnguyen3112** [comment]
Hello, have you fixed it yet?

**Comment by ProfJust** [comment]
Unfortunately not.   I tried to get it working with the new Gazebo (Ignition) at ROS2-Jazzy, but there I found the same problems,
As a workaround I fixed the Joints, so the gripper looks OK but cannot be opened/closed.

**Comment by nbbrooks** [comment]
For Gazebo Ignition issues involved mimic joints (used by Robotiq 2F and other devices), you should file an issue to https://github.com/ros-controls/gz_ros2_control asking which versions of gz-sim are expected to support mimic joints.
