### ISSUE TITLE
Is there a workaround to use this model with Ignition Gazebo Fortress?

### ISSUE THREAD

**Issue by PatrickReitz** [PickNikRobotics/ros2_robotiq_gripper#7]
Hi,
as far as i know Ignition Gazebo Fortress does not support mimic joints currently. Is there a workaround  to use this model with Ignition?

**Comment by moriarty** [comment]
This open Pull request is required https://github.com/ros-controls/gz_ros2_control/pull/86

**Comment by moriarty** [comment]
Linking this to upstream issue: gazebosim/gz-sim#1684

**Comment by nbbrooks** [comment]
Closing as this is a [gz-sim](https://github.com/ros-controls/gz_ros2_control) issue.
